#ifndef __TGdesk_delete_client_form__
#define __TGdesk_delete_client_form__

/**
@file
Subclass of delete_client_form, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing delete_client_form */
class TGdesk_delete_client_form : public delete_client_form
{
	protected:
		// Handlers for delete_client_form events.
		void add_client_formOnClose( wxCloseEvent& event );
		void add_client_formOnIconize( wxIconizeEvent& event );
		void del_buttonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		TGdesk_delete_client_form( wxWindow* parent );
	//// end generated class members







};

#endif // __TGdesk_delete_client_form__
