#ifndef __TGdesk_add_car_form__
#define __TGdesk_add_car_form__

/**
@file
Subclass of add_car_form, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/msgdlg.h>
#include "TGdesk_login_dial.h"

/** Implementing add_car_form */
class TGdesk_add_car_form : public add_car_form
{
	protected:
		// Handlers for add_car_form events.
		void add_car_formOnClose( wxCloseEvent& event );
		void nameOnChar( wxKeyEvent& event );
		void year_bOnChar( wxKeyEvent& event );
		void year_eOnChar( wxKeyEvent& event );
		void doors_numOnChar( wxKeyEvent& event );
		void seat_numOnChar( wxKeyEvent& event );
		void cargoOnChar( wxKeyEvent& event );
		void lengthOnChar( wxKeyEvent& event );
		void widthOnChar( wxKeyEvent& event );
		void heightOnChar( wxKeyEvent& event );
		void axesOnChar( wxKeyEvent& event );
		void fweelsOnChar( wxKeyEvent& event );
		void rweelsOnChar( wxKeyEvent& event );
		void descrOnChar( wxKeyEvent& event );
		void priceOnChar( wxKeyEvent& event );
		void phone_numOnChar( wxKeyEvent& event );
		void emailOnChar( wxKeyEvent& event );
		void descr_offerOnChar( wxKeyEvent& event );
		void backOnButtonClick( wxCommandEvent& event );
		void enterOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		TGdesk_add_car_form( wxWindow* parent );
	//// end generated class members

	protected:
	static bool is_num(const char c) {return c>='0' && c <='9';}
	bool dot = false;





































};

#endif // __TGdesk_add_car_form__
