#ifndef __TGdesk_eksport_client_form__
#define __TGdesk_eksport_client_form__

/**
@file
Subclass of eksport_client_form, which is generated by wxFormBuilder.
*/

#include "GUI.h"


#include "Backend_API.h"
#include <string>
#include <locale>
#include <codecvt>
#include <wx/msgdlg.h>
#include <wx/filedlg.h>
#include <wx/progdlg.h>
#include "TGdesk_main_frame.h"

//// end generated include

/** Implementing eksport_client_form */
class TGdesk_eksport_client_form : public eksport_client_form
{
	protected:
		// Handlers for eksport_client_form events.
		void eksport_client_formOnClose( wxCloseEvent& event );
		void eksport_client_formOnIconize( wxIconizeEvent& event );
		void nameOnChar( wxKeyEvent& event );
		void eksport_client_buttonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		TGdesk_eksport_client_form( wxWindow* parent );
	//// end generated class members

		private:
	Backend_API api;
	std::vector<std::string> ids;
	std::vector<std::string> email;

};

#endif // __TGdesk_eksport_client_form__
