#ifndef __TGdesk_import_client_form__
#define __TGdesk_import_client_form__

/**
@file
Subclass of import_client_form, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include <wx/msgdlg.h>



class TGdesk_import_client_form : public import_client_form
{
	protected:
		void import_client_formOnClose( wxCloseEvent& event );
		void import_client_formOnIconize( wxIconizeEvent& event );
		void choose_file_buttonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		TGdesk_import_client_form( wxWindow* parent );
	//// end generated class members





































};

#endif 
