#ifndef __TGdesk_import_car_form__
#define __TGdesk_import_car_form__

/**
@file
Subclass of import_car_form, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include <wx/msgdlg.h>


class TGdesk_import_car_form : public import_car_form
{
	protected:
		void import_car_formOnClose( wxCloseEvent& event );
		void import_car_formOnIconize( wxIconizeEvent& event );
		void choose_file_buttonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		TGdesk_import_car_form( wxWindow* parent );
	//// end generated class members





































};

#endif 
